const STORAGE='perfectProjectsDemoV1';
const seedJobs=[
 {id:'PP-1042',name:'Thabo M.',phone:'082 447 9216',suburb:'Durban North',service:'Plumbing',urgency:'high',budget:'R5,000 – R15,000',details:'Water is leaking under the kitchen sink and has started reaching the cabinet base. Shut-off valve is accessible.',path:'urgent',status:'new',quote:'',siteVisit:'',photos:['Leak photo','Cabinet area'],created:'Today · 08:12',notes:['Customer says someone is home all morning.'],reminder:true,activity:['08:12 · New urgent enquiry received','08:12 · Priority flag added automatically']},
 {id:'PP-1041',name:'Naledi P.',phone:'083 321 7750',suburb:'Umhlanga',service:'Bathroom renovation',urgency:'low',budget:'R80,000 – R150,000',details:'Main bathroom renovation. Wants walk-in shower, new vanity, floor and wall tiling. Existing layout can stay.',path:'planned',status:'quote',quote:'98500',siteVisit:'9 Sep · 14:00',photos:['Current bathroom','Shower area','Vanity'],created:'Yesterday · 16:44',notes:['Site visit completed. Client prefers warm neutral finishes.'],reminder:true,activity:['Yesterday · Enquiry received','Yesterday · Site visit scheduled','Today · Quote drafted']},
 {id:'PP-1040',name:'Chris B.',phone:'071 604 2298',suburb:'La Lucia',service:'Roofing & waterproofing',urgency:'medium',budget:'R15,000 – R40,000',details:'Leak appears above the lounge during heavy rain. Suspects waterproofing around roof junction.',path:'urgent',status:'visit',quote:'',siteVisit:'10 Sep · 09:30',photos:['Ceiling stain','Roof junction'],created:'Yesterday · 11:20',notes:['Asked to inspect before pricing.'],reminder:false,activity:['Yesterday · Enquiry received','Yesterday · Site visit booked for 10 Sep']},
 {id:'PP-1038',name:'Priya K.',phone:'076 990 1162',suburb:'Glenashley',service:'Tiling',urgency:'low',budget:'R40,000 – R80,000',details:'Replace downstairs floor tiles through living room and passage. Approx 70m².',path:'planned',status:'booked',quote:'62400',siteVisit:'Completed',photos:['Living room','Passage'],created:'2 Sep · 10:06',notes:['Deposit confirmed. Start date agreed.'],reminder:false,activity:['2 Sep · Enquiry received','3 Sep · Site visit completed','4 Sep · Quote sent: R62,400','6 Sep · Job marked booked — quote reminders stopped']}
];
let jobs=[]; let selectedId=null; let filter='all'; let path='urgent';
function loadJobs(){try{const saved=JSON.parse(localStorage.getItem(STORAGE));jobs=Array.isArray(saved)&&saved.length?saved:structuredClone(seedJobs)}catch(e){jobs=structuredClone(seedJobs)}selectedId=jobs[0]?.id||null}
function saveJobs(){localStorage.setItem(STORAGE,JSON.stringify(jobs))}
function showView(view){const customer=view==='customer';document.getElementById('customerView').classList.toggle('hidden',!customer);document.getElementById('dashboardView').classList.toggle('hidden',customer);document.getElementById('customerTab').classList.toggle('active',customer);document.getElementById('dashboardTab').classList.toggle('active',!customer);if(!customer){renderDashboard();window.scrollTo({top:0,behavior:'smooth'})}}
function choosePath(next){path=next;document.getElementById('urgentPath').classList.toggle('selected',next==='urgent');document.getElementById('plannedPath').classList.toggle('selected',next==='planned');document.querySelectorAll('.planned-only').forEach(el=>el.classList.toggle('hidden',next!=='planned'));document.getElementById('formTitle').textContent=next==='urgent'?'Urgent repair details':'Planned project details';document.getElementById('formSub').textContent=next==='urgent'?'A short brief so the team knows what they are walking into.':'A few details to qualify the project before a site visit or quote.';const urg=document.getElementById('urgency');urg.value=next==='urgent'?'high':'low'}
function prefillDemo(){document.getElementById('name').value=path==='urgent'?'Ayesha Khan':'Jason Smith';document.getElementById('phone').value='082 555 0188';document.getElementById('suburb').value=path==='urgent'?'Durban North':'Umhlanga';document.getElementById('service').value=path==='urgent'?'Plumbing':'Bathroom renovation';document.getElementById('urgency').value=path==='urgent'?'high':'low';document.getElementById('budget').value=path==='urgent'?'R5,000 – R15,000':'R80,000 – R150,000';document.getElementById('details').value=path==='urgent'?'Pipe under the basin is leaking and water is spreading into the vanity. I can send photos and someone is home today.':'We want to redo the main bathroom with a walk-in shower, new vanity and full retiling. Existing plumbing positions can mostly stay.';toast('Sample enquiry filled')}
document.getElementById('photos').addEventListener('change',e=>{const n=e.target.files.length;document.getElementById('uploadTitle').textContent=n?`${n} photo${n===1?'':'s'} selected`:'Add photos from your phone';document.getElementById('uploadText').textContent=n?Array.from(e.target.files).map(f=>f.name).slice(0,3).join(', '):'Photos help the team assess the job before replying.'});
document.getElementById('enquiryForm').addEventListener('submit',e=>{e.preventDefault();const files=Array.from(document.getElementById('photos').files).map((f,i)=>f.name||`Photo ${i+1}`);const urgency=document.getElementById('urgency').value;const id='PP-'+String(1043+jobs.filter(j=>Number(j.id?.split('-')[1])>=1043).length);const job={id,name:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),suburb:document.getElementById('suburb').value.trim(),service:document.getElementById('service').value,urgency,budget:document.getElementById('budget').value,details:document.getElementById('details').value.trim(),path,status:'new',quote:'',siteVisit:'',photos:files.length?files:['Photo upload placeholder'],created:'Just now',notes:[],reminder:false,activity:[`Just now · New ${urgency==='high'?'urgent ':''}enquiry received`,urgency==='high'?'Just now · Priority flag added automatically':'Just now · Added to new enquiries']};jobs.unshift(job);selectedId=id;saveJobs();document.getElementById('enquiryForm').classList.add('hidden');document.getElementById('successBox').classList.remove('hidden');document.getElementById('successSummary').innerHTML=`<div><b>Job</b><span>${esc(job.service)}</span></div><div><b>Area</b><span>${esc(job.suburb)}</span></div><div><b>Priority</b><span>${urgencyLabel(job.urgency)}</span></div><div><b>Reference</b><span>${job.id}</span></div>`;});
function renderDashboard(){renderKPIs();renderJobs();renderDetail()}
function renderKPIs(){document.getElementById('kpiOpen').textContent=jobs.filter(j=>j.status!=='booked').length;document.getElementById('kpiUrgent').textContent=jobs.filter(j=>j.urgency==='high'&&j.status!=='booked').length;document.getElementById('kpiQuotes').textContent=jobs.filter(j=>j.status==='quote'&&j.reminder).length;document.getElementById('kpiBooked').textContent=jobs.filter(j=>j.status==='booked').length}
function filteredJobs(){return jobs.filter(j=>filter==='all'||(filter==='high'&&j.urgency==='high')||(filter==='quote'&&j.status==='quote')||(filter==='visit'&&j.status==='visit'))}
function renderJobs(){const list=document.getElementById('jobsList');const arr=filteredJobs();if(!arr.length){list.innerHTML='<div class="empty">No jobs match this filter.</div>';return}list.innerHTML=arr.map(j=>`<div class="job-row ${j.id===selectedId?'active':''}" onclick="selectJob('${j.id}')"><div class="job-main"><div class="avatar">${initials(j.name)}</div><div class="job-name"><strong>${esc(j.name)} · ${esc(j.service)}</strong><span>${esc(j.suburb)} · ${j.id}</span></div></div><div class="cell"><span class="urgency ${j.urgency}">${urgencyLabel(j.urgency)}</span></div><div class="cell"><span class="status ${j.status}">${statusLabel(j.status)}</span></div><div class="cell">${esc(j.created)}</div><div class="chev">›</div></div>`).join('')}
function selectJob(id){selectedId=id;renderJobs();renderDetail()}
function renderDetail(){const j=jobs.find(x=>x.id===selectedId);const body=document.getElementById('detailBody');if(!j){body.innerHTML='<div class="empty">Select a job to view details.</div>';return}document.getElementById('detailStage').textContent=statusLabel(j.status);const nextMsg=followupMessage(j);body.innerHTML=`<div class="client-row"><div class="avatar">${initials(j.name)}</div><div><h3>${esc(j.name)}</h3><p>${esc(j.phone)} · ${esc(j.suburb)} · ${j.id}</p></div></div><div class="meta-grid"><div class="meta"><b>Service</b><span>${esc(j.service)}</span></div><div class="meta"><b>Priority</b><span>${urgencyLabel(j.urgency)}</span></div><div class="meta"><b>Budget</b><span>${esc(j.budget)}</span></div><div class="meta"><b>Site visit</b><span>${esc(j.siteVisit||'Not scheduled')}</span></div></div><div class="desc"><b>Customer brief</b><p>${esc(j.details)}</p></div><div class="photo-strip">${(j.photos||[]).slice(0,4).map(p=>`<div class="photo-thumb">▧<br>${esc(p)}</div>`).join('')}</div><div class="quote-box"><div class="quote-top"><b>Quote</b><span class="status ${j.quote?'quote':'new'}">${j.quote?'Draft / sent':'Not created'}</span></div><div class="quote-input"><input id="quoteAmount" inputmode="numeric" placeholder="Amount in R" value="${esc(j.quote||'')}"><button class="mini-btn" onclick="saveQuote('${j.id}')">Save quote</button></div></div><div class="followup"><div class="followup-top"><b>Follow-up preview</b><span class="reminder ${j.reminder?'':'off'}">${j.reminder?'Reminder active':'No reminder'}</span></div><div class="message">${esc(nextMsg)}</div></div><div class="action-grid"><button class="action primary-action" onclick="setStatus('${j.id}','quote')">Quote sent</button><button class="action" onclick="scheduleVisit('${j.id}')">Schedule site visit</button><button class="action" onclick="addNote('${j.id}')">Add note</button><button class="action book" onclick="setStatus('${j.id}','booked')">Mark job booked</button></div>${j.notes?.length?`<div class="activity"><h4>Notes</h4>${j.notes.map(n=>`<div class="event"><i></i><p>${esc(n)}</p></div>`).join('')}</div>`:''}<div class="activity"><h4>Activity</h4>${(j.activity||[]).slice().reverse().map(a=>`<div class="event"><i></i><p>${esc(a)}</p></div>`).join('')}</div>`}
function saveQuote(id){const val=document.getElementById('quoteAmount').value.replace(/[^0-9.]/g,'');const j=jobs.find(x=>x.id===id);if(!j)return;j.quote=val;j.status='quote';j.reminder=true;j.activity.push(`Now · Quote saved${val?' at R'+Number(val).toLocaleString('en-ZA'):''} · follow-up reminder activated`);saveJobs();renderDashboard();toast('Quote saved · follow-up activated')}
function setStatus(id,status){const j=jobs.find(x=>x.id===id);if(!j)return;j.status=status;if(status==='quote'){j.reminder=true;j.activity.push('Now · Quote marked sent · follow-up reminder activated')}if(status==='booked'){j.reminder=false;j.activity.push('Now · Job marked booked — quote reminders stopped automatically')}saveJobs();renderDashboard();toast(status==='booked'?'Job booked · reminders stopped':'Quote status updated')}
function scheduleVisit(id){const j=jobs.find(x=>x.id===id);if(!j)return;const when=prompt('Demo: enter site visit date/time','11 Sep · 10:00');if(!when)return;j.siteVisit=when;j.status='visit';j.reminder=false;j.activity.push(`Now · Site visit scheduled: ${when}`);saveJobs();renderDashboard();toast('Site visit scheduled')}
function addNote(id){const j=jobs.find(x=>x.id===id);if(!j)return;const note=prompt('Add an internal note');if(!note)return;j.notes=j.notes||[];j.notes.push(note);j.activity.push('Now · Internal note added');saveJobs();renderDashboard();toast('Note added')}
function followupMessage(j){if(j.status==='booked')return `Booked — no quote reminder will be sent. The next message can be a job confirmation or pre-start update.`;if(j.status==='visit')return `Hi ${firstName(j.name)}, just confirming your Perfect Projects site visit for ${j.siteVisit||'the scheduled time'}. If anything changes, reply here and we can update it.`;if(j.status==='quote')return `Hi ${firstName(j.name)}, just checking that you received the quote for your ${j.service.toLowerCase()} in ${j.suburb}. If you have any questions or want to adjust anything, just let us know.`;if(j.urgency==='high')return `Hi ${firstName(j.name)}, we received your urgent ${j.service.toLowerCase()} enquiry in ${j.suburb}. We already have the job details${j.photos?.length?', including your photos':''}, so the team can respond without asking you to repeat everything.`;return `Hi ${firstName(j.name)}, thanks for your enquiry about ${j.service.toLowerCase()} in ${j.suburb}. We have your job details and can now move straight to the right next step.`}
function setFilter(next,btn){filter=next;document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const arr=filteredJobs();if(!arr.some(j=>j.id===selectedId))selectedId=arr[0]?.id||null;renderJobs();renderDetail()}
function resetDemo(){if(!confirm('Reset the demo back to its original sample jobs?'))return;localStorage.removeItem(STORAGE);jobs=structuredClone(seedJobs);selectedId=jobs[0].id;filter='all';document.querySelectorAll('.filter').forEach((b,i)=>b.classList.toggle('active',i===0));document.getElementById('enquiryForm').reset();document.getElementById('enquiryForm').classList.remove('hidden');document.getElementById('successBox').classList.add('hidden');choosePath('urgent');saveJobs();renderDashboard();toast('Demo reset')}
function statusLabel(s){return({new:'New enquiry',quote:'Quote follow-up',visit:'Site visit',booked:'Booked'})[s]||s}
function urgencyLabel(s){return({high:'Urgent today',medium:'Soon',low:'Planned'})[s]||s}
function initials(name){return (name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function firstName(name){return (name||'there').split(/\s+/)[0].replace(/[^a-zA-Z'-]/g,'')||'there'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
let toastTimer;function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
loadJobs();choosePath('urgent');renderDashboard();
